language: node_js

node_js:
- '7'

notifications:
  email: false

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- sleep 1

before_script:
- npm rebuild phantomjs-prebuilt node-sass
- sleep 3

script:
- npm run lint
- npm run test:ci
- npm run coveralls

before_deploy:
- npm install -g github-release-notes
- npm install -g firebase-tools
- echo 'About to generate a new release note from commits...'
- gren --token=GREN_GITHUB_TOKEN
- echo 'About to deploy live...'
- npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    tags: true
  token:
    secure: US1eQ1vzKkOnEMMxDXVK8gqixMyw0dtNHMa8mOXTwRbxgIYUrZciW83LV3LRbowWCKWQKhPUxCKZ+XgLHItE2DNatvVIHOYU5wi/hkdGE8PdtRV0srFyH1+wGLUhInv+OCMhXk65FrVhoxf1WIqIykAU526w1OZfDuTEvpRrV+RY9IIOSy07m1rGZq+LKwKFNuNj8xYAgp8NDUHZ/aAG7VP8ZrnKxh/Y64ryQFhZAs82Fp7HJhK3oEZFIyBDVDiCxRBL8lTkDiM2Ve6mAmJfRBEkzbMv7h8tCjcquq2QtpTaqyhXxVnPzGphQsf6KATb10OVJfbUA6G/eP2ATyRn9V3/lEr6JFtk7EK8U+PgTNC1b5XJR75dxn2mYnvNh2x8KVPc0ND/9AiibXLCYGUoRtciSl9IwQfUNQXkomH1FEWO3z9W0kVmwMvsdT9et0PGGLeo7VbJ4aqNADlfM8YamVQQ25DThPphsCIS8Qg2S/RJ4OhFH3s90ZFBMLh/0pLcgfLpzkr5olxfd5g7E1qmDqvKpiMpFH7wgSA2IyNiX93LW5IKSxkUXHAr6a/StpbaS7CHUp3/VrRBidFpEiOEzzG3PV1l+HQHKq5Jwgzk52o6NRs6jE5KRr/JasrJf54FESDwMfUK/BctfPeqI3hFiQ6Wrl5W2XjlXpNSlKlEu28=
  project: online-board

env:
  global:
    secure: Ghns9/vFdFkA+sir8vG5hQHHiq68r63/kBJY2SsWtdq4WjisqsW7Ab+YX6qZfhx0dyCCcRp1rK99wAW7ndnZTH0QNW3IKc01GVKUiUsFoX5Oo4XTr18It2RL49FlO47JDimoy4z6hbBeY6ZZR4uLI9S3zBw1TY4ZDwz99DDdnoowCqz47DkspNbnMbLQuMJFkJ0awx7O4iqfd92uYDZZEkDsU/fFi7qt/jgVrbtD2Q/X+fd+wCTvBI8qrtH+88PfSNUMeUNeS4avP/aTnlUeVwFqpMhj1/pN+9P7Nn0Y7Amh5mvHmtUHPL7OvUjVHUG73Th8FnkBLwiom4ITuyKtv2Z5ZYy49PzWfhJm+JIQfRQpYYv5VDf8if97u4KH5Rup6V6IWgUm1OWoCUndLaCJPbVhyifBXQ4PulJdmfErmAPoDs6bB3LNrU7zco4OTyvAelbZeSaMOz5zhlix0lS0/KMoGqgtOg4PkLN6bmD1OthQX6qxRDyvvRWDAn+NeEICGTJBPS1YwQrIpVFtsmkSpnOqKczDXNQrKvyo7DE6oqrNP1sbroxU3vUBSC2w6DU8MUryFK03CBNi+l35/Nn8tCOZCtsk7fnqc77k426qr6OZtaXyqEMXviXbl9JTGqAsbitoW6QmKMZmBSiAWux2LzkleEmKFok8HF7QcRyq9E0=
